---
title: "Funciones de varias variables"
author: "Luis Mendoza"
format:
  revealjs:
    transition: slide
---

## Introducción

Una función de una variable es una regla de correspondencia que asigna a cada elemento $x$ en el subconjunto $X$ de números reales (llamado *dominio* de $f$), uno y solo un número real $y$ en otro conjunto de números reales $Y$ (llamado *rango* de $f$).

A la variable que que definamos como la que conforma el *dominio* le conocemos como la **variable independiente**, mientras que la variable incluída en el conjunto $Y$ se le nombra **variable dependiente**.

---

Una función de dos variables es una regla de correspondencia que asigna a cada par de números reales ($x$, $y$), uno y solo un número real $z$ dentro del conjunto de valores $R$, correspondientes a la variable dependiente.

Solo debe haber una variable dependiente mientras puede haber infinidad de independientes.

## Funciones polinomiales y racionales

Una **función polinomial** de dos variables consiste en la suma de potencias $x^m y^n$, donde $m$ y $n$ son enteros no negativos. Por ejemplo:

$$f(x,y)=xy-5x^2+9$$

El cociente de dos funciones polinomiales se denomina **función racional**. Por ejemplo:

$$f(x,y)=\frac{1}{xy-3y}$$

---

El dominio de una función polinomial es el plano $xy$ completo.

El dominio de una función racional es el plano $xy$, excepto los pares de números que vuelvan nulo al denominador.

---

Hagamos un breve repaso de las funciones simples, para así pasar a las de varias variables. Por ejemplo, tomemos la función $f(x)=3x^2+4x$ y evaluemos $f(5)$ y $f(-7)$:

$$
f(5)=3(5)^2+4(5)=75+20=95
$$

$$
f(-7)=3(-7)^2+4(-7)=147-28=119
$$

## Intro a Sympy

Sympy es una librería de *Python* que sirve para realizar operaciones matemáticas simbólicas de alto nivel. Puede instalarse utilizando el comando recomendado para el sistema operativo que usemos. Por ejemplo, para Windows:

```bash
pip install sympy
```

Al tenerla instalada, podemos cargar Sympy de la manera usual:

```{python}
#| echo: True
import sympy
```

---

Los comandos necesarios para crear una función en Sympy pasan por crear primero la variable simbólica. Para ello, primero:

```{python}
#| echo: True
# Importamos lo necesario
from sympy import symbols

# Creamos la variable simbólica
x = sympy.symbols('x')

# Creamos la expresión matemática
expr_f = 5 / x

# Y la volvemos función
f = sympy.Lambda(x, expr_f)
```

---

Y para valuar la función, escribimos su nombre con el valor de la variable independiente como argumento:

```{python}
#| echo: True
# Valúemos para f(15)
f(15)
```

Podemos expresar el resultado sin que sea una fracción:

```{python}
#| echo: True
# Escribimos el resultado con tres decimales
sympy.N(f(15),3)

```

## Dominio y rango de una función bivariable

1. Dada $f(x,y) = 4 + \sqrt{x^2 - y^2}$, encontremos $f(1,0)$, $f(5,3)$ y $f(4,-2)$.
2. Encontremos el dominio de la función.
3. Obtengamos el rango de la función.

---

Primero preparemos la función simbólica:

```{python}
#| echo: True
# Cargamos lo necesario
import sympy as sp

# Creamos las variables simbólicas
x = sp.symbols('x')
y = sp.symbols('y')

# Creamos la expresión
expr = 4 + sp.sqrt(x**2 - y**2)

# Creamos la función simbólica
f = sp.Lambda((x,y), expr)
```
---

Valuemos la función para los tres pares de valores propuestos:

```{python}
#| echo: True
# Valuamos para f(1,0)
f(1,0)
```

```{python}
#| echo: True
# Para f(5,3)
f(5,3)
```

```{python}
#| echo: True
# Y para f(4,-2)
sp.N(f(4,-2),3)
```

---

Para los puntos 2 y 3, tendremos que confiar en nuestra capacidad de análisis, ya que Sympy no puede graficar funciones bivariables ni calcular el dominio y rango de estas funciones.

---

Lo que sí puede es encontrar las singularidades de la función para cada variable:

```{python}
#| echo: True
print("Singularidades respecto x: ", sp.calculus.singularities(f(x,y), x))
print("Singularidades respecto y: ", sp.calculus.singularities(f(x,y), y))

Rx = sp.calculus.util.function_range(f(x,1), x, sp.Reals)
Ry = sp.calculus.util.function_range(f(1,y), y, sp.Reals)
Ryn = sp.calculus.util.function_range(f(-1,y), y, sp.Reals)
display(Rx)
display(Ry)
display(Ryn)
```


